name: Coverage

on:
  push:
    branches:
      - main

jobs:
  testsCover:
    runs-on: ubuntu-latest

    steps:
      - name: update
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_VPS_IP }}
          username: ${{ secrets.PROD_VPS_USER }}
          password: ${{ secrets.PROD_VPS_PASS }}

          script: |
            cd /avito/backend-bootcamp-assignment-2024
            git pull

      - name: database
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_VPS_IP }}
          username: ${{ secrets.PROD_VPS_USER }}
          password: ${{ secrets.PROD_VPS_PASS }}

          script: |
            cd /avito/backend-bootcamp-assignment-2024
            
            docker compose up db --build -d
            
            export GOPATH=$HOME/go
            export PATH=$PATH:$GOROOT/bin:$GOPATH/binexport GOPATH=$HOME/goexport PATH=$PATH:$GOROOT/bin:$GOPATH/bin

            goose -dir ./migrations postgres "postgresql://makarov:simplePassword@localhost:20500/bootcamp?sslmode=disable" up

      - name: coverage
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_VPS_IP }}
          username: ${{ secrets.PROD_VPS_USER }}
          password: ${{ secrets.PROD_VPS_PASS }}

          script: |
            cd /avito/backend-bootcamp-assignment-2024

            go test ./... -coverprofile coverage.out
            COVERAGE=`go tool cover -func=coverage.out | grep total: | grep -Eo '[0-9]+\.[0-9]+'`
            echo $COVERAGE